name: Run Unit test per commit
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on: [push]
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test
